env:
  global:
    - LC_CTYPE=en_US.UTF-8
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode9
      before_install:
        - brew install swiftlint
      script:
        - swiftlint
        - swift test
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq clang curl git libblocksruntime0 libcurl4-openssl-dev libedit2 libicu55 libkqueue0 libpython2.7-dev libxml2 python2.7 tzdata uuid-dev
        - git submodule update --init --recursive
        - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
        - wget https://swift.org/builds/swift-4.0-release/ubuntu1404/swift-4.0-RELEASE/swift-4.0-RELEASE-ubuntu14.04.tar.gz
        - tar xzf swift-4.0-RELEASE-ubuntu14.04.tar.gz
        - wget https://github.com/realm/SwiftLint/archive/0.23.1.tar.gz -O swiftlint.tar.gz
        - tar xzf swiftlint.tar.gz
        - cd SwiftLint-0.23.1 && ../swift-4.0-RELEASE-ubuntu14.04/usr/bin/swift build && cd ..
      script:
        - LINUX_SOURCEKIT_LIB_PATH=${PWD}/swift-4.0-RELEASE-ubuntu14.04/usr/lib ${PWD}/SwiftLint-0.23.1/.build/debug/swiftlint
        - ${PWD}/swift-4.0-RELEASE-ubuntu14.04/usr/bin/swift test
